# Generated by Django 5.0.1 on 2024-08-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=40)),
                ('price', models.CharField(max_length=2)),
                ('plate_number', models.IntegerField(max_length=5)),
                ('filled_gas', models.IntegerField(max_length=3)),
                ('Date', models.DateField(auto_now_add=True)),
                ('employe_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='oil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=15)),
                ('changed_oil', models.CharField(max_length=3)),
                ('plate_number', models.IntegerField(max_length=5)),
                ('Date', models.DateField(auto_now_add=True)),
                ('employe_name', models.CharField(max_length=15)),
            ],
        ),
    ]
