# Generated by Django 5.0.1 on 2024-08-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baksapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oil',
            name='plate_number',
            field=models.IntegerField(),
        ),
    ]
