# Generated by Django 5.0.1 on 2024-08-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baksapp', '0002_alter_oil_plate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='filled_gas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='plate_number',
            field=models.IntegerField(),
        ),
    ]
